Error in search_food: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
Error in search_food: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
Error in search_food: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
Error in search_food: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
Error in get_nutrition: [Errno 2] No such file or directory: 'data/FoodIngredient.xlsx'
Error in get_nutrition: [Errno 2] No such file or directory: 'data/FoodIngredient.xlsx'
Error in get_nutrition: [Errno 2] No such file or directory: 'data/FoodIngredient.xlsx'
Error in get_nutrition: [Errno 2] No such file or directory: 'data/FoodIngredient.xlsx'
Error in get_nutrition: [Errno 2] No such file or directory: 'data/FoodIngredient.xlsx'
Error in get_nutrition: [Errno 2] No such file or directory: 'data/FoodIngredient.xlsx'
Error in get_nutrition: [Errno 2] No such file or directory: 'data/FoodIngredient.xlsx'
Error in get_nutrition: [Errno 2] No such file or directory: 'data/FoodIngredient.xlsx'
Error in get_nutrition: [Errno 2] No such file or directory: 'data/FoodIngredient.xlsx'
Error in get_nutrition: [Errno 2] No such file or directory: 'data/FoodIngredient.xlsx'
Error in get_nutrition: [Errno 2] No such file or directory: 'data/FoodIngredient.xlsx'
Error in get_nutrition: [Errno 2] No such file or directory: 'data/FoodIngredient.xlsx'
Error in get_nutrition: [Errno 2] No such file or directory: 'data/FoodIngredient.xlsx'
Error in get_nutrition: [Errno 2] No such file or directory: 'data/FoodIngredient.xlsx'
Error in get_nutrition: [Errno 2] No such file or directory: 'data/FoodIngredient.xlsx'
Error in get_nutrition: 'Food Code'
Error in get_nutrition: 'Food Code'
Error in get_nutrition: 'Food Code'
Error in get_nutrition: 'Food Code'
Error in get_nutrition: 'Food Code'
Error in get_nutrition: 'Food Code'
Error in get_nutrition: 'Food Code'
Error in get_nutrition: only list-like objects are allowed to be passed to isin(), you passed a `int`
Error in get_ingredients: 'Ingredient Code'
Error in get_ingredients: int() argument must be a string, a bytes-like object or a real number, not 'list'
Error in get_ingredients: int() argument must be a string, a bytes-like object or a real number, not 'list'
Error in get_ingredients: int() argument must be a string, a bytes-like object or a real number, not 'list'
Error in get_ingredients: int() argument must be a string, a bytes-like object or a real number, not 'list'
Error in get_ingredients: 'int' object is not iterable
Exception on /runchart [POST]
Traceback (most recent call last):
  File "/Users/seon/Desktop/CambodiaNAS/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/app.py", line 279, in run_python_code
    result = bar(current_meal_data)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/bar.py", line 9, in bar
    recommends=pd.read_excel('data/NutritionRecommends.xlsx')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/venv/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 495, in read_excel
    io = ExcelFile(
         ^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/venv/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 1550, in __init__
    ext = inspect_excel_format(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/venv/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 1402, in inspect_excel_format
    with get_handle(
         ^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/venv/lib/python3.12/site-packages/pandas/io/common.py", line 882, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/NutritionRecommends.xlsx'
Exception on /runchart [POST]
Traceback (most recent call last):
  File "/Users/seon/Desktop/CambodiaNAS/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/app.py", line 279, in run_python_code
    result = bar(current_meal_data)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/bar.py", line 9, in bar
    recommends=pd.read_excel('data/NutritionRecommends.xlsx')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/venv/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 495, in read_excel
    io = ExcelFile(
         ^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/venv/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 1550, in __init__
    ext = inspect_excel_format(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/venv/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 1402, in inspect_excel_format
    with get_handle(
         ^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/venv/lib/python3.12/site-packages/pandas/io/common.py", line 882, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/NutritionRecommends.xlsx'
Exception on /runchart [POST]
Traceback (most recent call last):
  File "/Users/seon/Desktop/CambodiaNAS/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/app.py", line 280, in run_python_code
    return render_template('24h_chart.html', result=result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/venv/lib/python3.12/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/venv/lib/python3.12/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/seon/Desktop/CambodiaNAS/venv/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/seon/Desktop/CambodiaNAS/templates/24h_chart.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/Users/seon/Desktop/CambodiaNAS/templates/base.html", line 31, in top-level template code
    {% block content %}
  File "/Users/seon/Desktop/CambodiaNAS/templates/24h_chart.html", line 6, in block 'content'
    {% include 'radarchart.html' %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/venv/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/venv/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: radarchart.html
